remote-control:
    control-enable: yes
    control-interface: "/etc/unbound/run/unbound.sock"

server:
    verbosity: 0
    interface: 0.0.0.0
    port: 53
    access-control: 127.0.0.0/8 allow
    access-control: 10.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow
    access-control: 0.0.0.0/0 refuse

    do-ip6: no
    do-daemonize: no
    username: "dnstrust"
    chroot: ""
    directory: "/etc/unbound"
    pidfile: "/run/dnstrust/unbound.pid"
    use-syslog: yes

    include: "/etc/unbound/module-config.conf"
    auto-trust-anchor-file: "/var/lib/dnstrust/root.key"
    filter-database: "/var/lib/dnstrust/blacklist.db"

    num-threads: 4
    so-reuseport: yes
    msg-cache-size: 256m
    rrset-cache-size: 512m
    key-cache-size: 128m
    neg-cache-size: 64m
    cache-min-ttl: 0
    cache-max-ttl: 86400
    prefetch: yes
    prefetch-key: yes
    serve-expired: yes
    minimal-responses: yes
    qname-minimisation: yes
    edns-buffer-size: 1232
    hide-identity: yes
    hide-version: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-below-nxdomain: yes
    deny-any: yes

    local-zone: "use-application-dns.net." always_nxdomain
    local-zone: "blacklist." blacklist
    local-data: "blacklist. 10800 IN NS nobody.blacklist."
    local-data: "blacklist. 10800 IN SOA blacklist. nobody.invalid. 1 3600 1200 604800 10800"
    local-data: "blacklist. 60 IN HINFO 'BLOCKED' 'Komdigi Trust Positif'"
    local-data: "blacklist. 60 IN TXT 'BLOCKED - Komdigi Trust Positif'"

    include: "/etc/unbound/lamanlabuh.conf"
    include: "/etc/unbound/whitelist.conf"
    include: "/etc/unbound/local.conf"
    include: "/etc/unbound/forwarder.conf"
    include: "/etc/unbound/safesearch.conf"
    include: "/etc/unbound/hosts.conf"
    include: "/etc/unbound/tproxy.conf"
