local-zone: "mail-abuse.com." whitelist
local-zone: "spamhaus.org." whitelist
local-zone: "spamcop.net." whitelist
local-zone: "dnswl.org." whitelist
local-zone: "manitu.net." whitelist
local-zone: "sorbs.net." whitelist
local-zone: "abuseat.org." whitelist
local-zone: "surriel.com." whitelist
local-zone: "surbl.org." whitelist
local-zone: "google.com." whitelist
local-zone: "youtube.com." whitelist
local-zone: "yahoo.com." whitelist
local-zone: "yahoodns.net." whitelist
local-zone: "facebook.com." whitelist
local-zone: "twitter.com." whitelist
local-zone: "msn.com." whitelist
local-zone: "bing.com." whitelist
local-zone: "tiktokcdn.com." whitelist
local-zone: "tikokcdn-us.com." whitelist
local-zone: "tiktokv.com." whitelist
local-zone: "gstatic.com." whitelist
local-zone: "googleapis.com." whitelist
local-zone: "wikimedia.com." whitelist
local-zone: "vimeo.com." whitelist
local-zone: "microsoft.com." whitelist
local-zone: "apple.com." whitelist
local-zone: "whatsapp.com." whitelist
local-zone: "instagram.com." whitelist
local-zone: "vivoglobal.com." whitelist
local-zone: "akamai.net." whitelist
local-zone: "akamaihd.net." whitelist
local-zone: "akamaiedge.net." whitelist
local-zone: "edgekey.net." whitelist
local-zone: "edgesuite.net." whitelist
local-zone: "akadns.net." whitelist
local-zone: "fbcdn.net." whitelist
local-zone: "amazon.com." whitelist
local-zone: "amazonaws.com." whitelist
local-zone: "amazontrust.com." whitelist
local-zone: "amazonvideo.com." whitelist
local-zone: "media-amazon.com." whitelist
local-zone: "amazon-adsystem.com." whitelist
local-zone: "cloudfront.net." whitelist
local-zone: "barracudacentral.com." whitelist
local-zone: "barracudacentral.org." whitelist
local-zone: "bondedsender.org." whitelist
local-zone: "telegram.org." whitelist
local-zone: "t.me." whitelist
local-zone: "telegram.me." whitelist
local-zone: "tumblr.com." whitelist
local-zone: "kat.cr." whitelist
local-zone: "steam-api.com." whitelist
local-zone: "steam-chat.com." whitelist
local-zone: "steamcommunity.com." whitelist
local-zone: "steampowered.com." whitelist
local-zone: "steamstatic.com." whitelist
local-zone: "dota2.com." whitelist
local-zone: "counter-strike.net." whitelist
local-zone: "epicgames.com." whitelist
local-zone: "origin.com." whitelist
local-zone: "xandr.com." whitelist
local-zone: "paypal-mktg.com." whitelist
